### test PostgREST endpoint
GET http://localhost:8090/users

### test get specific user
GET http://localhost:8090/users?email=eq.admin@email.com&password=eq.123

### post
POST http://localhost:8080/register-submit
Content-Type:application/x-www-form-urlencoded

email=josh@example.com&password=123&username=josh&matchingPassword=123

### do login by post
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

email=admin@email.com&password=123